// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwipAuMMW0B6b5JYHdkd2qqA1jpxadec',
    appId: '1:68532369864:web:7ebe7a4ec687b935d728fd',
    messagingSenderId: '68532369864',
    projectId: 'cashtrack-c130b',
    authDomain: 'cashtrack-c130b.firebaseapp.com',
    storageBucket: 'cashtrack-c130b.firebasestorage.app',
    measurementId: 'G-LQ14FP3B2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVfUGlfK3ManVCJh8X9Be7k2IdmDQkZA',
    appId: '1:68532369864:android:732643e7f759b52dd728fd',
    messagingSenderId: '68532369864',
    projectId: 'cashtrack-c130b',
    storageBucket: 'cashtrack-c130b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNia3xZHO1OS60KZjTDFYPEFUpH-QlL9I',
    appId: '1:68532369864:ios:1133d06d8587aebbd728fd',
    messagingSenderId: '68532369864',
    projectId: 'cashtrack-c130b',
    storageBucket: 'cashtrack-c130b.firebasestorage.app',
    iosClientId: '68532369864-j7p196lg0a82u9lqcn5jqncd8lqhtel6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNia3xZHO1OS60KZjTDFYPEFUpH-QlL9I',
    appId: '1:68532369864:ios:1133d06d8587aebbd728fd',
    messagingSenderId: '68532369864',
    projectId: 'cashtrack-c130b',
    storageBucket: 'cashtrack-c130b.firebasestorage.app',
    iosClientId: '68532369864-j7p196lg0a82u9lqcn5jqncd8lqhtel6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashtrack',
  );

}